name:                viwrap
version:             0.1.0.0
github:              "githubuser/viwrap"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

description:         Please see the README on GitHub at <https://github.com/githubuser/viwrap#readme>

flags:
  prod:
    manual: True
    default: False

dependencies:
- ansi-terminal
- async
- base >= 4.7 && < 5
- bytestring
- containers
- freer-simple
- process
- microlens
- microlens-th
- unix
- utf8-string

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DerivingStrategies 
- GADTs
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TypeFamilies

ghc-options:
- -fprint-explicit-foralls
- -fprint-explicit-kinds
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-deriving-strategies
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-foralls
- -Wmissing-local-signatures

library:
  source-dirs: src
  when:
    - condition: flag(prod)
      then:
        ghc-options:
          -Werror
          -O3
      else:
        ghc-options:
          -Wwarn

language: GHC2021

executables:
  viwrap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - viwrap

tests:
  viwrap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - viwrap
